CREATE TABLE [dbo].[BILLINGDETAILFILE](
	[BILLDNO] INTEGER NOT NULL UNIQUE,
	[BILLDCOUNT] INTEGER NOT NULL,
	[BILLDESC] TEXT, 
	[BILLDAMOUNT] DECIMAL(5,2) NOT NULL,
	[BILLDSTATUS] TEXT NOT NULL,

	PRIMARY KEY(BILLDNO, BILLDCOUNT)
);