CREATE TABLE [dbo].[PRESCRIPTIONDETAILFILE](
	[PREDCODE] INTEGER NOT NULL UNIQUE,
	[PREDMEDCODE] INTEGER NOT NULL UNIQUE,
	[PREDQTY] INTEGER NOT NULL,
	[PREDREMARKS] TEXT NOT NULL,
	[PREDSTATUS] TEXT NOT NULL,

	PRIMARY KEY(PREDCODE, PREDMEDCODE)
);